compatibility_date = "2025-03-14"

[[ env.development.d1_databases ]]
binding = "FEED_DB"
database_name = "kiranbrahma-cms_feed_db_production"
database_id = "3a3db98e-706b-4471-ab8c-17795096a6f6"

[env.production]

[env.preview]
