export const BUILT_IN_FIXTURES: Record<string, Record<string, unknown>> = {
  public_tags: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Public tag archive",
    home_page_url: "https://example.test/tags/世界/",
    feed_url: "https://example.test/tags/世界/json/",
    items: [{id: "tagged", title: "A tagged item", tags: ["世界 🌍"], _microfeed: {
      web_url: "https://example.test/i/tagged/",
      tags: [{id: "tag-one", name: "世界 🌍", slug: "世界", url: "https://example.test/tags/世界/", rss_url: "https://example.test/tags/世界/rss/", json_url: "https://example.test/tags/世界/json/"}],
    }}],
    _microfeed: {base_url: "https://example.test", categories: [], microfeed_version: "preview", subscribe_methods: [],
      tag: {id: "tag-one", name: "世界 🌍", slug: "世界", description: "A public topic", published_item_count: 1, url: "https://example.test/tags/世界/", rss_url: "https://example.test/tags/世界/rss/", json_url: "https://example.test/tags/世界/json/"}},
    search: {query: "世界", results: [{id: "tag-one", title: "世界 🌍", type: "tag", url: "https://example.test/tags/世界/"}]},
  },
  empty: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Empty feed",
    home_page_url: "https://example.test/",
    items: [],
  },
  tags_empty: {
    version: "https://jsonfeed.org/version/1.1", title: "Empty tag directory", home_page_url: "https://example.test/", items: [],
    tags: {title: "Tags", url: "https://example.test/tags/", items: [], rss_enabled: true, json_enabled: true},
  },
  tags_directory: {
    version: "https://jsonfeed.org/version/1.1", title: "Tag directory site", home_page_url: "https://example.test/", items: [],
    tags: {title: "Tags", url: "https://example.test/tags/", rss_enabled: false, json_enabled: true,
      next_url: "https://example.test/tags/?next_cursor=next",
      items: [{id: "directory-tag", name: "世界 <b> 🌍", slug: "世界", description: "<script>Plain-text description</script>", published_item_count: 0,
        url: "https://example.test/tags/%E4%B8%96%E7%95%8C/", rss_url: "https://example.test/tags/%E4%B8%96%E7%95%8C/rss/", json_url: "https://example.test/tags/%E4%B8%96%E7%95%8C/json/"}],
    },
  },
  minimal: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Minimal feed",
    home_page_url: "https://example.test/",
    items: [{id: "one", title: "Hello", content_text: "A short post."}],
  },
  rich: {
    version: "https://jsonfeed.org/version/1.1",
    title: "A very long feed title intended to exercise wrapping in narrow viewports",
    description: "Rich content and long text",
    home_page_url: "https://example.test/",
    items: [{id: "rich", title: "Rich content", content_html: "<p><strong>Bold</strong>, <em>italic</em>, and a <a href=\"https://example.test/\">link</a>.</p>", _microfeed: {web_url: "https://example.test/i/rich/"}}],
  },
  pagination: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Paginated feed",
    next_url: "https://example.test/json/?next_cursor=next",
    items: [{id: "page", title: "Page item", content_text: "More pages follow."}],
    _microfeed: {items_next_cursor: "next", items_order: "desc", items_sort: "published_at"},
  },
  media: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Media feed",
    items: [
      {id: "audio", title: "Audio", attachments: [{url: "https://example.test/audio.mp3", mime_type: "audio/mpeg", duration_in_seconds: 90}], _microfeed: {is_audio: true}},
      {id: "video", title: "Video", attachments: [{url: "https://example.test/video.mp4", mime_type: "video/mp4"}], _microfeed: {is_video: true}},
      {id: "image", title: "Image", image: "https://example.test/image.jpg", _microfeed: {is_image: true}},
      {id: "document", title: "Document", attachments: [{url: "https://example.test/document.pdf", mime_type: "application/pdf"}], _microfeed: {is_document: true}},
      {id: "external", title: "External", external_url: "https://example.test/article", _microfeed: {is_external_url: true}},
    ],
  },
  missing_optional: {
    version: "https://jsonfeed.org/version/1.1",
    items: [{id: "missing", title: "Only required fields"}],
  },
  authors_and_subscriptions: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Many authors",
    authors: [{name: "Ada"}, {name: "Grace"}],
    items: [{id: "authors", title: "Authored", authors: [{name: "Ada"}]}],
    _microfeed: {subscribe_methods: [{name: "RSS", url: "https://example.test/rss/"}, {name: "JSON Feed", url: "https://example.test/json/"}]},
  },
  hostile_html: {
    version: "https://jsonfeed.org/version/1.1",
    title: "Trusted-code fixture",
    items: [{id: "hostile", title: "Potentially hostile HTML", content_html: "<img src=x onerror=\"document.body.dataset.fixture='executed'\"><script>document.documentElement.dataset.fixtureScript='executed'</script>"}],
  },
};
