import {env} from "cloudflare:workers";
import {describe, expect, it} from "vitest";

import {installationInstanceId} from "@/server/installation-identity";

describe("installation identity", () => {
  it("creates one stable UUID when deployment configuration omits the id", async () => {
    const first = await installationInstanceId(env.FEED_DB);
    const second = await installationInstanceId(env.FEED_DB);

    expect(first).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u,
    );
    expect(second).toBe(first);
  });

  it("preserves the explicit id generated by yarn admin", async () => {
    const configured = crypto.randomUUID();

    await expect(
      installationInstanceId(env.FEED_DB, configured),
    ).resolves.toBe(configured);
    await expect(installationInstanceId(env.FEED_DB)).resolves.toBe(configured);
  });
});
