/// <reference path="./worker-configuration.d.ts" />

import type FeedCrudManager from "@/server/feed/FeedCrudManager";
import type FeedDb from "@/server/feed/FeedDb";
import type {
  AdminProtectionStatus,
  FeedContent,
  OnboardingResult,
} from "./types";

declare module "react" {
  interface Component<P, S> {
    [member: string]: any;
  }
}

declare global {
  // The repository build configuration supplies defaults. Configurations
  // generated by `yarn manage` may override these deployment settings.
  interface Env {
    BETTER_AUTH_SECRET: string;
    DEPLOYMENT_ENVIRONMENT?: "preview" | "production";
    MICROFEED_ADMIN_AUTH_MODE?: "built-in" | "none";
    MICROFEED_ADMIN_PATH?: string;
    MICROFEED_CLOUDFLARE_ACCOUNT_ID?: string;
    MICROFEED_INSTANCE_ID?: string;
    MICROFEED_R2_BUCKET_NAME?: string;
    MICROFEED_WORKER_NAME?: string;
    MICROFEED_SETUP_ADMIN_EMAIL?: string;
    MICROFEED_SETUP_ADMIN_PASSWORD?: string;
    MICROFEED_SETUP_ADMIN_PASSWORD_CONFIRMATION?: string;
    TEST_MIGRATIONS?: D1Migration[];
    UPLOAD_SIGNING_KEY: string;
  }

  namespace Cloudflare {
    interface Env {
      BETTER_AUTH_SECRET: string;
      DEPLOYMENT_ENVIRONMENT?: "preview" | "production";
      MICROFEED_ADMIN_AUTH_MODE?: "built-in" | "none";
      MICROFEED_ADMIN_PATH?: string;
      MICROFEED_CLOUDFLARE_ACCOUNT_ID?: string;
      MICROFEED_INSTANCE_ID?: string;
      MICROFEED_R2_BUCKET_NAME?: string;
      MICROFEED_WORKER_NAME?: string;
      MICROFEED_SETUP_ADMIN_EMAIL?: string;
      MICROFEED_SETUP_ADMIN_PASSWORD?: string;
      MICROFEED_SETUP_ADMIN_PASSWORD_CONFIRMATION?: string;
      TEST_MIGRATIONS?: D1Migration[];
      UPLOAD_SIGNING_KEY: string;
    }
  }

  namespace App {
    interface Locals {
      adminProtection?: AdminProtectionStatus;
      authSession?: import("better-auth").Session;
      authUser?: import("better-auth").User;
      feedContent?: FeedContent;
      feedCrud?: FeedCrudManager;
      feedDb?: FeedDb;
      onboardingResult?: OnboardingResult;
      publicBucketUrl?: string;
    }
  }
}

export {};
